name: Load Test Pipeline with JMeter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre unzip msmtp
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xvzf apache-jmeter-5.6.3.tgz
        sudo mv apache-jmeter-5.6.3 /opt/jmeter
        echo "JMeter installed!"

    - name: Run JMeter Load Test
      run: |
        mkdir -p ./jmeter-results
        /opt/jmeter/bin/jmeter -n -t sDir_TestScript_Git.jmx -l ./jmeter-results/result.jtl -e -o ./jmeter-results/report
        echo "JMeter test completed!"

    - name: Configure msmtp for Email
      run: |
        # Configure msmtp with Gmail (replace with your SMTP details)
        echo "defaults" > ~/.msmtprc
        echo "account gmail" >> ~/.msmtprc
        echo "host smtp.gmail.com" >> ~/.msmtprc
        echo "port 587" >> ~/.msmtprc
        echo "from akshathas@symplr.com" >> ~/.msmtprc
        echo "user akshathas@symplr.com" >> ~/.msmtprc
        echo "password ${{ secrets.EMAIL_PASSWORD }}" >> ~/.msmtprc
        echo "tls on" >> ~/.msmtprc
        echo "tls_starttls on" >> ~/.msmtprc
        echo "logfile ~/.msmtp.log" >> ~/.msmtprc
        chmod 600 ~/.msmtprc
        echo "msmtp configured!"

    - name: Send Email with Report
      run: |
        # Send an email with the HTML report as an attachment
        echo -e "Subject:JMeter Load Test Report\nContent-Type: text/html\n\n\
        <h1>JMeter Load Test Completed</h1>\
        <p>Please find the test results below:</p>\
        <a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>View full report</a>" | msmtp --attachment="./jmeter-results/report/index.html" akshathas@symplr.com
        echo "Email sent successfully!"
