name: Load Test Pipeline with JMeter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xvzf apache-jmeter-5.6.3.tgz
        sudo mv apache-jmeter-5.6.3 /opt/jmeter
        echo "JMeter installed!"
    - name: Install JMeter Plugin
      run: |
        # Download the JMeter plugin for JMeter
        wget https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.10/jmeter-plugins-manager-1.10.jar
        sudo mv jmeter-plugins-manager-1.10.jar /opt/jmeter/lib/ext/
        echo "JMeter Plugins Manager installed!"

    - name: Install BlazeMeter Plugin
      run: |
        # Define JMeter Home
        export JMETER_HOME=/opt/jmeter
        
        # Install BlazeMeter Plugin (which includes the Parallel Controller)
        java -cp $JMETER_HOME/lib/ext/jmeter-plugins-manager-1.10.jar org.jmeterplugins.repository.PluginManagerCMDInstaller install bzm-parallel-controller
        echo "BlazeMeter plugin installed!"

    - name: Run JMeter Load Test
      run: |
        # Create the jmeter-results folder in the current directory (repo root)
        mkdir -p ./jmeter-results
        
        # Create the jmeter-results folder
        # mkdir -p jmeter-results
        # Run the JMeter test and save the result.jtl and report inside jmeter-results
        /opt/jmeter/bin/jmeter -n -t sDir_TestScript_Git.jmx -l ./jmeter-results/result.jtl -e -o ./jmeter-results/report

    - name: Upload JMeter Report
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-report
        path: ./jmeter-results/report

    - name: View JMeter Test Results
      run: |
        cat ./jmeter-results/result.jtl
