name: Load Test Pipeline with JMeter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre unzip
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xvzf apache-jmeter-5.6.3.tgz
        sudo mv apache-jmeter-5.6.3 /opt/jmeter
        echo "JMeter installed!"

    - name: Install JMeter Plugins Manager
      run: |
        export JMETER_HOME=/opt/jmeter

        # Install the necessary dependencies for the Plugin Manager
        wget -L https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.0/cmdrunner-2.0.jar -P $JMETER_HOME/lib/
        wget -L https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.10/jmeter-plugins-manager-1.10.jar -P $JMETER_HOME/lib/ext/
        echo "JMeter Plugins Manager installed!"

    - name: Install BlazeMeter Plugin (Parallel Controller)
      run: |
        export JMETER_HOME=/opt/jmeter

        # Ensure the Plugin Manager is available
        if [ ! -f $JMETER_HOME/lib/ext/jmeter-plugins-manager-1.10.jar ]; then
          echo "Plugin Manager not installed!"
          exit 1
        fi

        # Install BlazeMeter Parallel Controller plugin
        echo "Installing BlazeMeter Parallel Controller plugin..."
        java -cp $JMETER_HOME/lib/ext/jmeter-plugins-manager-1.10.jar org.jmeterplugins.repository.PluginManagerCMDInstaller install bzm-parallel-controller
        echo "BlazeMeter Parallel Controller plugin installed successfully!"

        # List contents of JMeter lib/ext to verify plugin files are present
        ls $JMETER_HOME/lib/ext/

    - name: Verify JMeter Test Script
      run: |
        if [ ! -f sDir_TestScript_Git.jmx ]; then
          echo "JMeter test script not found!"
          exit 1
        fi

    - name: Run JMeter Load Test
      run: |
        # Verify JMeter is running with the correct environment
        echo "Verifying JMeter setup..."
        /opt/jmeter/bin/jmeter -v

        # Ensure the plugin files are in the lib/ext directory
        ls /opt/jmeter/lib/ext/

        # Run the test script
        mkdir -p ./jmeter-results
        /opt/jmeter/bin/jmeter -n -t sDir_TestScript_Git.jmx -l ./jmeter-results/result.jtl -e -o ./jmeter-results/report

    - name: Upload JMeter Report
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-report
        path: ./jmeter-results/report

    - name: View JMeter Test Results
      run: |
        cat ./jmeter-results/result.jtl
