name: Load Test Pipeline with JMeter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre unzip
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xvzf apache-jmeter-5.6.3.tgz
        sudo mv apache-jmeter-5.6.3 /opt/jmeter
        echo "JMeter installed!"

    - name: Download and Install BlazeMeter Parallel Controller Plugin
      run: |
        export JMETER_HOME=/opt/jmeter

        # Download the BlazeMeter Parallel Controller plugin ZIP file
        wget https://jmeter-plugins.org/files/packages/bzm-parallel-0.12.zip -P /tmp/

        # Unzip the plugin into JMeter's lib/ext directory
        sudo unzip /tmp/bzm-parallel-0.12.zip -d $JMETER_HOME/lib/ext/
        echo "BlazeMeter Parallel Controller plugin installed successfully!"
         
    - name: Run JMeter Load Test
      run: |
        # Create the jmeter-results folder in the current directory (repo root)
        mkdir -p ./jmeter-results
        
        # Create the jmeter-results folder
        # mkdir -p jmeter-results
        # Run the JMeter test and save the result.jtl and report inside jmeter-results
        /opt/jmeter/bin/jmeter -n -t sDir_TestScript_Git.jmx -l ./jmeter-results/result.jtl -e -o ./jmeter-results/report

    - name: Upload JMeter Report
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-report
        path: ./jmeter-results/report

    - name: View JMeter Test Results
      run: |
        cat ./jmeter-results/result.jtl
       
