name: Run JMeter with BZM Parallel Controller on Windows

on:
  push:
    branches:
      - main

jobs:
  run_jmeter:
    runs-on: windows-latest  # Runs the job on Windows OS

    steps:
      # Step 1: Checkout the repository containing the JMeter test plan
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install JMeter on Windows
      - name: Set up JMeter
        run: |
          Invoke-WebRequest -Uri "https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.4.1.zip" -OutFile "apache-jmeter-5.4.1.zip"
          Expand-Archive -Path "apache-jmeter-5.4.1.zip" -DestinationPath "C:/"
          $env:PATH += ";C:/apache-jmeter-5.4.1/bin"

      # Step 3: Install BZM Parallel Controller Plugin (if necessary)
      - name: Install BZM Parallel Controller plugin
        run: |
          $pluginUrl = "https://github.com/Blazemeter/parallel-controller/releases/download/1.0/bzm-parallel-controller-1.0.jar"
          $pluginPath = "C:/apache-jmeter-5.4.1/lib/ext/bzm-parallel-controller-1.0.jar"
          Invoke-WebRequest -Uri $pluginUrl -OutFile $pluginPath

      # Step 4: Run the JMeter test plan using BZM Parallel Controller
      - name: Run JMeter test with BZM Parallel Controller
        run: |
          jmeter -n -t sDir_TestScript.jmx -l result.jtl -e -o results

      # Step 5: Upload JMeter Results to GitHub Actions
      - name: Upload JMeter results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results
