name: Load Test Pipeline with JMeter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xvzf apache-jmeter-5.6.3.tgz
        sudo mv apache-jmeter-5.6.3 /opt/jmeter
        echo "JMeter installed!"

    - name: Run JMeter Load Test
      run: |
        mkdir -p ./jmeter-results
        /opt/jmeter/bin/jmeter -n -t Sample_1.jmx -l ./jmeter-results/result.jtl -e -o ./jmeter-results/report
        echo "JMeter test completed!"

    - name: Send Email with Report (using sendmail)
      run: |
        SUBJECT="JMeter Load Test Report"
        TO="akshathas@symplr.com"
        FROM="akshathas@symplr.com"
        HTML_REPORT="./jmeter-results/report/index.html"

        echo "Subject: $SUBJECT\nFrom: $FROM\nTo: $TO\nContent-Type: text/html; charset=UTF-8\n\n\
        <h1>JMeter Load Test Completed</h1>\n\
        <p>Please find the test results below:</p>\n\
        <a href='https://github.com/yourusername/yourrepository/actions/runs/${{ github.run_id }}'>View full report</a>" | \
        sendmail -a "$HTML_REPORT" "$TO"

        echo "Email sent successfully!"
