name: Load Test Pipeline with JMeter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xvzf apache-jmeter-5.6.3.tgz
        sudo mv apache-jmeter-5.6.3 /opt/jmeter
        echo "JMeter installed!"

    - name: Run JMeter Load Test
      run: |
        # Create the jmeter-results folder in the current directory (repo root)
        mkdir -p ./jmeter-results
        
        # Create the jmeter-results folder
        # mkdir -p jmeter-results
        # Run the JMeter test and save the result.jtl and report inside jmeter-results
        /opt/jmeter/bin/jmeter -n -t Sample.jmx -l /jmeter-demo/jmeter-results/result.jtl -e -o /jmeter-demo/jmeter-results/report

    - name: Upload JMeter Report
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-report
        path: jmeter-demo/jmeter-results/report

    - name: View JMeter Test Results
      run: |
        cat /jmeter-demo/jmeter-results/result.jtl
